// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.Data.Context;

namespace Repository.Migrations
{
    [DbContext(typeof(SonnyDbContext))]
    [Migration("20220630223214_partnerrelationship")]
    partial class partnerrelationship
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("Domain.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("Complement")
                        .HasColumnType("longtext");

                    b.Property<string>("District")
                        .HasColumnType("longtext");

                    b.Property<string>("Number")
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.Property<string>("Street")
                        .HasColumnType("longtext");

                    b.Property<string>("ZipCode")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "null",
                            Complement = "null",
                            District = "null",
                            Number = "null",
                            State = "null",
                            Street = "null",
                            ZipCode = "null"
                        },
                        new
                        {
                            Id = 2,
                            City = "Belo Horizonte",
                            Complement = "",
                            District = "Santa Efigênia",
                            Number = "123",
                            State = "MG",
                            Street = "R. Padre Rolim",
                            ZipCode = "31255-080"
                        },
                        new
                        {
                            Id = 3,
                            City = "Belo Horizonte",
                            Complement = " sala 801",
                            District = "Floresta",
                            Number = "32",
                            State = "MG",
                            Street = " R. Curvelo",
                            ZipCode = "31015-172"
                        },
                        new
                        {
                            Id = 4,
                            City = "Belo Horizonte",
                            Complement = "",
                            District = "Funcionários",
                            Number = "446",
                            State = "MG",
                            Street = "Av. Getúlio Vargas",
                            ZipCode = "30112-020"
                        },
                        new
                        {
                            Id = 5,
                            City = "Belo Horizonte",
                            Complement = "",
                            District = "Pompéia",
                            Number = "95",
                            State = "MG",
                            Street = "R. Veredinha",
                            ZipCode = "30280-520"
                        },
                        new
                        {
                            Id = 6,
                            City = "Belo Horizonte",
                            Complement = "",
                            District = "Horizontes",
                            Number = "4678",
                            State = "MG",
                            Street = "R. Camanducaia",
                            ZipCode = "98989-4856"
                        },
                        new
                        {
                            Id = 7,
                            City = "-------------",
                            Complement = "",
                            District = "-------------",
                            Number = "-------------",
                            State = "-------------",
                            Street = "-------------",
                            ZipCode = "-------------"
                        },
                        new
                        {
                            Id = 8,
                            City = "Belo Horizonte",
                            Complement = "",
                            District = "Milionários",
                            Number = "25",
                            State = "MG",
                            Street = " R. Maringá",
                            ZipCode = "30620-270"
                        });
                });

            modelBuilder.Entity("Domain.Entities.BusinessBox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("InventoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("SoldAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("Today")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("InventoryId");

                    b.ToTable("BusinessBoxes");
                });

            modelBuilder.Entity("Domain.Entities.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Checkcode")
                        .HasColumnType("int");

                    b.Property<int?>("CheckingAccountId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Flag")
                        .HasColumnType("longtext");

                    b.Property<string>("Holder")
                        .HasColumnType("longtext");

                    b.Property<string>("Numbercard")
                        .HasColumnType("longtext");

                    b.Property<string>("Typeaccount")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Validate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CheckingAccountId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Processadores"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Memórias"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Armazenamento"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fonte"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Placa Mãe"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Monitor"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Teclado"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Mouse"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Cooler"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Placa de Video"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Placa de rede"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Adaptador"
                        });
                });

            modelBuilder.Entity("Domain.Entities.CheckingAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Account")
                        .HasColumnType("int");

                    b.Property<int>("Agency")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Holder")
                        .HasColumnType("longtext");

                    b.Property<string>("Institution")
                        .HasColumnType("longtext");

                    b.Property<string>("Manager")
                        .HasColumnType("longtext");

                    b.Property<string>("Pix")
                        .HasColumnType("longtext");

                    b.Property<string>("Typeaccount")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CheckingAccounts");
                });

            modelBuilder.Entity("Domain.Entities.ClientEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<bool>("Assured")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CNPJ")
                        .HasColumnType("longtext");

                    b.Property<string>("ClientType")
                        .HasColumnType("longtext");

                    b.Property<string>("Comments")
                        .HasColumnType("longtext");

                    b.Property<int>("ContactId")
                        .HasColumnType("int");

                    b.Property<bool>("Disabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Payment")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Responsible")
                        .HasColumnType("longtext");

                    b.Property<bool>("ToBusinessBox")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ToSeach")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("ContactId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Domain.Entities.CollectDeliver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasColumnType("longtext");

                    b.Property<int>("DestinyAddressId")
                        .HasColumnType("int");

                    b.Property<string>("Items")
                        .HasColumnType("longtext");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("SourceAddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("TransporterId")
                        .HasColumnType("int");

                    b.Property<string>("TransporterNoregisterd")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DestinyAddressId");

                    b.HasIndex("SourceAddressId");

                    b.HasIndex("TransporterId");

                    b.ToTable("CollectsDelivers");
                });

            modelBuilder.Entity("Domain.Entities.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cel")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Landline")
                        .HasColumnType("longtext");

                    b.Property<string>("Site")
                        .HasColumnType("longtext");

                    b.Property<string>("Zap")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cel = "null",
                            Email = "null",
                            Landline = "null",
                            Zap = "null"
                        },
                        new
                        {
                            Id = 2,
                            Cel = "(31) 9-8859-8734",
                            Email = "lucas@laenderevianna.com.br",
                            Landline = "(31) 2516-2327",
                            Zap = "(31) 9-8859-8734"
                        },
                        new
                        {
                            Id = 3,
                            Cel = "(31) 9-9851-1532",
                            Email = "oppen@oppeninformatica.com.br",
                            Landline = "(31) 3234-4661",
                            Zap = "(31) 9-9851-1532"
                        },
                        new
                        {
                            Id = 4,
                            Cel = "(31) 9-9851-1532",
                            Email = "oppen@oppeninformatica.com.br",
                            Landline = "(31) 3234-4661",
                            Zap = "(31) 9-9851-1532"
                        },
                        new
                        {
                            Id = 5,
                            Cel = "(31) 9-8553-2934",
                            Email = "comercial@perfectprint.com.br",
                            Landline = "(31) 3272-7620",
                            Zap = "(31) 9-8553-2934"
                        },
                        new
                        {
                            Id = 6,
                            Cel = "(31) 9-9999-9999",
                            Email = "marcelo@marcelomotoca.com.br",
                            Landline = "(31) 9999-9999",
                            Zap = "(31) 9-9999-9999"
                        },
                        new
                        {
                            Id = 7,
                            Cel = "-------------",
                            Email = "-------------",
                            Landline = "-------------",
                            Zap = "-------------"
                        },
                        new
                        {
                            Id = 8,
                            Cel = "",
                            Email = "comercial@comercialrosasantos.com.br",
                            Landline = "(31) 2512-6346",
                            Zap = ""
                        });
                });

            modelBuilder.Entity("Domain.Entities.DailyInFlow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Amount")
                        .HasColumnType("longtext");

                    b.Property<int>("CheckingaccountId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Today")
                        .HasColumnType("longtext");

                    b.Property<int>("TypepaymentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CheckingaccountId");

                    b.HasIndex("ClientId");

                    b.HasIndex("TypepaymentId");

                    b.ToTable("DailyInFlows");
                });

            modelBuilder.Entity("Domain.Entities.DailyOutFlow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Amount")
                        .HasColumnType("longtext");

                    b.Property<int>("CheckingaccountId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("PersonOrPlace")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Today")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TypepaymentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CheckingaccountId");

                    b.HasIndex("TypepaymentId");

                    b.ToTable("DailyOutFlows");
                });

            modelBuilder.Entity("Domain.Entities.DestinyCollectDeliver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("NoRegisterAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("NoRegisterName")
                        .HasColumnType("longtext");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("PartnerId");

                    b.ToTable("DestinyCollectDelivers");
                });

            modelBuilder.Entity("Domain.Entities.EletronicRepair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Authorized")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Finished")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Item")
                        .HasColumnType("longtext");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Problem")
                        .HasColumnType("longtext");

                    b.Property<string>("User")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("day")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("solution")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId");

                    b.ToTable("EletronicsRepairs");
                });

            modelBuilder.Entity("Domain.Entities.ImgPath", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("NetworkDeviceId")
                        .HasColumnType("int");

                    b.Property<string>("img")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("NetworkDeviceId");

                    b.ToTable("ImgPath");
                });

            modelBuilder.Entity("Domain.Entities.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Capacity")
                        .HasColumnType("longtext");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Driver")
                        .HasColumnType("longtext");

                    b.Property<string>("Generation")
                        .HasColumnType("longtext");

                    b.Property<string>("Historical")
                        .HasColumnType("longtext");

                    b.Property<bool>("Isnew")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Istested")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Manufactorer")
                        .HasColumnType("longtext");

                    b.Property<string>("Model")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Saleprice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Sn")
                        .HasColumnType("longtext");

                    b.Property<string>("Speed")
                        .HasColumnType("longtext");

                    b.Property<int>("SubCategoryid")
                        .HasColumnType("int");

                    b.Property<int>("Supplierid")
                        .HasColumnType("int");

                    b.Property<string>("ToSeach")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Today")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Today_")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubCategoryid");

                    b.HasIndex("Supplierid");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("Domain.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Domain.Entities.MonthlyOutFlow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Amount")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Duplicateurl")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Installment")
                        .HasColumnType("int");

                    b.Property<string>("Institution")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Started")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("User")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MonthlyOutFlows");
                });

            modelBuilder.Entity("Domain.Entities.NetworkDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Apps")
                        .HasColumnType("longtext");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Connectivity")
                        .HasColumnType("longtext");

                    b.Property<string>("Door")
                        .HasColumnType("longtext");

                    b.Property<string>("Equipament")
                        .HasColumnType("longtext");

                    b.Property<string>("Ip")
                        .HasColumnType("longtext");

                    b.Property<string>("Mac")
                        .HasColumnType("longtext");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("longtext");

                    b.Property<string>("Model")
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("PhysicalLocation")
                        .HasColumnType("longtext");

                    b.Property<string>("Sn")
                        .HasColumnType("longtext");

                    b.Property<string>("ToSeach")
                        .HasColumnType("longtext");

                    b.Property<string>("User")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("NetworkDevices");
                });

            modelBuilder.Entity("Domain.Entities.OsRemoveEquipament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Client")
                        .HasColumnType("longtext");

                    b.Property<string>("Equipament")
                        .HasColumnType("longtext");

                    b.Property<string>("Model")
                        .HasColumnType("longtext");

                    b.Property<string>("Problem")
                        .HasColumnType("longtext");

                    b.Property<string>("Pwd")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Usr")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("OsRemoveEquipament");
                });

            modelBuilder.Entity("Domain.Entities.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("BusinessLine")
                        .HasColumnType("longtext");

                    b.Property<string>("CNPJ")
                        .HasColumnType("longtext");

                    b.Property<string>("Comments")
                        .HasColumnType("longtext");

                    b.Property<int>("ContactId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Responsible")
                        .HasColumnType("longtext");

                    b.Property<string>("ToSeach")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Today")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("ContactId");

                    b.ToTable("Partners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 1,
                            BusinessLine = "null",
                            CNPJ = "null",
                            Comments = "null",
                            ContactId = 1,
                            Name = "null",
                            Responsible = "null",
                            ToSeach = "null",
                            Today = new DateTime(2022, 6, 30, 19, 32, 13, 135, DateTimeKind.Local).AddTicks(1742)
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 5,
                            BusinessLine = "Assistência técnica, aluguel e venda de periféricos e impressoras",
                            CNPJ = "",
                            Comments = "",
                            ContactId = 5,
                            Name = "Perfect print",
                            Responsible = "Luiz Junior",
                            ToSeach = "Perfect print Luiz Junior",
                            Today = new DateTime(2022, 6, 30, 19, 32, 13, 136, DateTimeKind.Local).AddTicks(6583)
                        },
                        new
                        {
                            Id = 3,
                            AddressId = 6,
                            BusinessLine = "Motoboy faz e desfaz qualquer treta!",
                            CNPJ = "",
                            Comments = "De confiança!",
                            ContactId = 6,
                            Name = "Marcelinho Motoca",
                            Responsible = "Marcelo Duarte",
                            ToSeach = "Perfect print Luiz Junior",
                            Today = new DateTime(2022, 6, 30, 19, 32, 13, 136, DateTimeKind.Local).AddTicks(6629)
                        });
                });

            modelBuilder.Entity("Domain.Entities.ServiceBudget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("ClientProblems")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EntryDateOs")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Entrydate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Finished")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("OsMake")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("Visually")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("ServicesBudgets");
                });

            modelBuilder.Entity("Domain.Entities.SocialNetwork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ContactId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.ToTable("socialnetworks");
                });

            modelBuilder.Entity("Domain.Entities.SolutionPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Authorized")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateService")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PriceService")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("Remote")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ServiceBudgetId")
                        .HasColumnType("int");

                    b.Property<bool>("Solved")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TechnicalSolution")
                        .HasColumnType("longtext");

                    b.Property<string>("Technician")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ServiceBudgetId");

                    b.ToTable("SolutionsPrices");
                });

            modelBuilder.Entity("Domain.Entities.SourceCollectDeliver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("NoRegisterAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("NoRegisterName")
                        .HasColumnType("longtext");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("PartnerId");

                    b.ToTable("SourceCollectDelivers");
                });

            modelBuilder.Entity("Domain.Entities.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategories");
                });

            modelBuilder.Entity("Domain.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<int>("ContactId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Operation")
                        .HasColumnType("longtext");

                    b.Property<string>("Seller")
                        .HasColumnType("longtext");

                    b.Property<string>("ToSeach")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("ContactId");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 7,
                            ContactId = 7,
                            Name = "BaseDeTroca",
                            Seller = "....",
                            ToSeach = "Origem desconhecida"
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 3,
                            ContactId = 3,
                            Name = "Oppen Informática",
                            Seller = "Juliano",
                            ToSeach = "Oppen Informática Juliano"
                        },
                        new
                        {
                            Id = 3,
                            AddressId = 4,
                            ContactId = 4,
                            Name = "Oficina dos Bits",
                            Seller = "Leonardo",
                            ToSeach = "Oficina dos Bits Leonardo"
                        });
                });

            modelBuilder.Entity("Domain.Entities.SupplierTypePayment", b =>
                {
                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<int>("TypePaymentId")
                        .HasColumnType("int");

                    b.HasKey("SupplierId", "TypePaymentId");

                    b.HasIndex("TypePaymentId");

                    b.ToTable("SuppliersTypesPayments");

                    b.HasData(
                        new
                        {
                            SupplierId = 1,
                            TypePaymentId = 1
                        },
                        new
                        {
                            SupplierId = 1,
                            TypePaymentId = 2
                        },
                        new
                        {
                            SupplierId = 2,
                            TypePaymentId = 1
                        },
                        new
                        {
                            SupplierId = 2,
                            TypePaymentId = 2
                        },
                        new
                        {
                            SupplierId = 2,
                            TypePaymentId = 3
                        },
                        new
                        {
                            SupplierId = 2,
                            TypePaymentId = 4
                        });
                });

            modelBuilder.Entity("Domain.Entities.TypePayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TypesPayments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Pagamento em espécie.",
                            Name = "Dinheiro"
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            Name = "Pix"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Débito",
                            Name = "Débito"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Credito",
                            Name = "Credito"
                        });
                });

            modelBuilder.Entity("Domain.Entities.BusinessBox", b =>
                {
                    b.HasOne("Domain.Entities.ClientEntity", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.HasOne("Domain.Entities.Inventory", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryId");

                    b.Navigation("Client");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("Domain.Entities.Card", b =>
                {
                    b.HasOne("Domain.Entities.CheckingAccount", null)
                        .WithMany("Cards")
                        .HasForeignKey("CheckingAccountId");
                });

            modelBuilder.Entity("Domain.Entities.ClientEntity", b =>
                {
                    b.HasOne("Domain.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("Domain.Entities.CollectDeliver", b =>
                {
                    b.HasOne("Domain.Entities.DestinyCollectDeliver", "DestinyAddress")
                        .WithMany("CollectsDelivers")
                        .HasForeignKey("DestinyAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.SourceCollectDeliver", "SourceAddress")
                        .WithMany("CollectsDelivers")
                        .HasForeignKey("SourceAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Partner", "Transporter")
                        .WithMany("CollectsDelivers")
                        .HasForeignKey("TransporterId");

                    b.Navigation("DestinyAddress");

                    b.Navigation("SourceAddress");

                    b.Navigation("Transporter");
                });

            modelBuilder.Entity("Domain.Entities.DailyInFlow", b =>
                {
                    b.HasOne("Domain.Entities.CheckingAccount", "Checkingaccount")
                        .WithMany()
                        .HasForeignKey("CheckingaccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ClientEntity", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TypePayment", "Typepayment")
                        .WithMany()
                        .HasForeignKey("TypepaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Checkingaccount");

                    b.Navigation("Client");

                    b.Navigation("Typepayment");
                });

            modelBuilder.Entity("Domain.Entities.DailyOutFlow", b =>
                {
                    b.HasOne("Domain.Entities.CheckingAccount", "Checkingaccount")
                        .WithMany()
                        .HasForeignKey("CheckingaccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TypePayment", "Typepayment")
                        .WithMany()
                        .HasForeignKey("TypepaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Checkingaccount");

                    b.Navigation("Typepayment");
                });

            modelBuilder.Entity("Domain.Entities.DestinyCollectDeliver", b =>
                {
                    b.HasOne("Domain.Entities.ClientEntity", "Client")
                        .WithMany("DestinyCollectDelivers")
                        .HasForeignKey("ClientId");

                    b.HasOne("Domain.Entities.Partner", "Partner")
                        .WithMany("DestinyCollectDelivers")
                        .HasForeignKey("PartnerId");

                    b.Navigation("Client");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("Domain.Entities.EletronicRepair", b =>
                {
                    b.HasOne("Domain.Entities.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("Domain.Entities.ImgPath", b =>
                {
                    b.HasOne("Domain.Entities.NetworkDevice", null)
                        .WithMany("Images")
                        .HasForeignKey("NetworkDeviceId");
                });

            modelBuilder.Entity("Domain.Entities.Inventory", b =>
                {
                    b.HasOne("Domain.Entities.SubCategory", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("Supplierid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubCategory");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Domain.Entities.NetworkDevice", b =>
                {
                    b.HasOne("Domain.Entities.ClientEntity", "Client")
                        .WithMany("NetworksDevices")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Domain.Entities.Partner", b =>
                {
                    b.HasOne("Domain.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("Domain.Entities.ServiceBudget", b =>
                {
                    b.HasOne("Domain.Entities.ClientEntity", "Client")
                        .WithMany("ServicesBudgets")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Domain.Entities.SocialNetwork", b =>
                {
                    b.HasOne("Domain.Entities.Contact", null)
                        .WithMany("socialnetworks")
                        .HasForeignKey("ContactId");
                });

            modelBuilder.Entity("Domain.Entities.SolutionPrice", b =>
                {
                    b.HasOne("Domain.Entities.ServiceBudget", "ServiceBudget")
                        .WithMany("SolutionsPrices")
                        .HasForeignKey("ServiceBudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceBudget");
                });

            modelBuilder.Entity("Domain.Entities.SourceCollectDeliver", b =>
                {
                    b.HasOne("Domain.Entities.ClientEntity", "Client")
                        .WithMany("SourceCollectDelivers")
                        .HasForeignKey("ClientId");

                    b.HasOne("Domain.Entities.Partner", "Partner")
                        .WithMany("SourceCollectDelivers")
                        .HasForeignKey("PartnerId");

                    b.Navigation("Client");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("Domain.Entities.SubCategory", b =>
                {
                    b.HasOne("Domain.Entities.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Entities.Supplier", b =>
                {
                    b.HasOne("Domain.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("Domain.Entities.SupplierTypePayment", b =>
                {
                    b.HasOne("Domain.Entities.Supplier", "Supplier")
                        .WithMany("SuppliersTypesPayments")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TypePayment", "TypePayment")
                        .WithMany()
                        .HasForeignKey("TypePaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");

                    b.Navigation("TypePayment");
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Domain.Entities.CheckingAccount", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("Domain.Entities.ClientEntity", b =>
                {
                    b.Navigation("DestinyCollectDelivers");

                    b.Navigation("NetworksDevices");

                    b.Navigation("ServicesBudgets");

                    b.Navigation("SourceCollectDelivers");
                });

            modelBuilder.Entity("Domain.Entities.Contact", b =>
                {
                    b.Navigation("socialnetworks");
                });

            modelBuilder.Entity("Domain.Entities.DestinyCollectDeliver", b =>
                {
                    b.Navigation("CollectsDelivers");
                });

            modelBuilder.Entity("Domain.Entities.NetworkDevice", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Domain.Entities.Partner", b =>
                {
                    b.Navigation("CollectsDelivers");

                    b.Navigation("DestinyCollectDelivers");

                    b.Navigation("SourceCollectDelivers");
                });

            modelBuilder.Entity("Domain.Entities.ServiceBudget", b =>
                {
                    b.Navigation("SolutionsPrices");
                });

            modelBuilder.Entity("Domain.Entities.SourceCollectDeliver", b =>
                {
                    b.Navigation("CollectsDelivers");
                });

            modelBuilder.Entity("Domain.Entities.Supplier", b =>
                {
                    b.Navigation("SuppliersTypesPayments");
                });
#pragma warning restore 612, 618
        }
    }
}
