// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.Data.Context;

namespace Repository.Migrations
{
    [DbContext(typeof(SonnyDbContext))]
    [Migration("20231130110022_financial1")]
    partial class financial1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("Domain.Entities.Authentication.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("aspnetUserRoles");
                });

            modelBuilder.Entity("Domain.Entities.Fill.StkProduct.Equipament_Fill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Equipament")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Equipament")
                        .IsUnique();

                    b.ToTable("PD_Equipament_Fillers");
                });

            modelBuilder.Entity("Domain.Entities.Fill.StkProduct.Manufacturer_Fill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Manufacturer")
                        .IsUnique();

                    b.ToTable("PD_Manufacturer_Fillers");
                });

            modelBuilder.Entity("Domain.Entities.Fill.StkProduct.Segment_Fill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Segment")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Segment")
                        .IsUnique();

                    b.ToTable("PD_Segment_Fillers");
                });

            modelBuilder.Entity("Domain.Entities.Finances.FinancialBankAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Account")
                        .HasColumnType("longtext");

                    b.Property<string>("Agency")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Holder")
                        .HasColumnType("longtext");

                    b.Property<string>("Institution")
                        .HasColumnType("longtext");

                    b.Property<string>("ManagerContact")
                        .HasColumnType("longtext");

                    b.Property<string>("ManagerName")
                        .HasColumnType("longtext");

                    b.Property<string>("Pix")
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("FN_BankAccount");
                });

            modelBuilder.Entity("Domain.Entities.Finances.FinancialCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BankAccountId")
                        .HasColumnType("int");

                    b.Property<int>("CheckCode")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Flag")
                        .HasColumnType("longtext");

                    b.Property<string>("Holder")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Limit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Number")
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("Validate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BankAccountId");

                    b.ToTable("FN_Cards");
                });

            modelBuilder.Entity("Domain.Entities.Finances.FinancialEssentialExpenses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BankAccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EntryRegister")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ExpensesId")
                        .HasColumnType("int");

                    b.Property<decimal>("Interest")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("PaidBy")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WasPaid")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BankAccountId");

                    b.HasIndex("ExpensesId");

                    b.HasIndex("UserId");

                    b.ToTable("FN_EssentialExpenses");
                });

            modelBuilder.Entity("Domain.Entities.Finances.FinancialExpenses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("CyclePayment")
                        .HasColumnType("int");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LinkCopyBill")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("NameIdentification")
                        .HasColumnType("longtext");

                    b.Property<int>("NumberInstallment")
                        .HasColumnType("int");

                    b.Property<string>("PASSLinkCopyBill")
                        .HasColumnType("longtext");

                    b.Property<string>("USERLinkCopyBill")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("FN_Expenses");
                });

            modelBuilder.Entity("Domain.Entities.Finances.FinancialExpensesNotPredictable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BankAccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DaySpent")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EntryRegister")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ExpensesId")
                        .HasColumnType("int");

                    b.Property<string>("ItemOrPlaceName")
                        .HasColumnType("longtext");

                    b.Property<int>("PaidBy")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BankAccountId");

                    b.HasIndex("ExpensesId");

                    b.HasIndex("UserId");

                    b.ToTable("FN_ExpensesNotPredictable");
                });

            modelBuilder.Entity("Domain.Entities.Main.Companies.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<int?>("ContactId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("ContactId");

                    b.ToTable("MN_Companies");
                });

            modelBuilder.Entity("Domain.Entities.Main.Customers.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<bool>("Assured")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("BusinessLine")
                        .HasColumnType("longtext");

                    b.Property<string>("CNPJ")
                        .HasColumnType("longtext");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("ContactId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerType")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("Disabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Expiration")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Payment")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("PhysicallyMovingCostsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Registered")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Responsible")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ContactId");

                    b.HasIndex("PhysicallyMovingCostsId");

                    b.ToTable("MN_Customers");
                });

            modelBuilder.Entity("Domain.Entities.Main.Inheritances.PhysicallyMovingCosts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Apps")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("FixedCostAssured")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Fuel")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("MotoBoy")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PublicTransport")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("MN_PhysicallyMovingCosts");
                });

            modelBuilder.Entity("Domain.Entities.Main.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("BusinessLine")
                        .HasColumnType("longtext");

                    b.Property<string>("CNPJ")
                        .HasColumnType("longtext");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("ContactId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("PartnerType")
                        .HasColumnType("int");

                    b.Property<int?>("PhysicallyMovingCostsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Registered")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Responsible")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ContactId");

                    b.HasIndex("PhysicallyMovingCostsId");

                    b.ToTable("MN_Partners");
                });

            modelBuilder.Entity("Domain.Entities.Outsourced.BillingFrom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Base")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PartnerId");

                    b.ToTable("OS_BillingsFroms");
                });

            modelBuilder.Entity("Domain.Entities.Outsourced.CollectDeliver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("BillingFromId")
                        .HasColumnType("int");

                    b.Property<bool>("Collect")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("ContactName")
                        .HasColumnType("longtext");

                    b.Property<bool>("Deliver")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Other")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SubjectReason")
                        .HasColumnType("longtext");

                    b.Property<string>("TaskOverView")
                        .HasColumnType("longtext");

                    b.Property<int?>("TransporterId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BillingFromId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("TransporterId");

                    b.HasIndex("UserId");

                    b.ToTable("OS_CollectsDelivers");
                });

            modelBuilder.Entity("Domain.Entities.Outsourced.Destiny", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CollectDeliverId")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("NoRegisterAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("NoRegisterName")
                        .HasColumnType("longtext");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CollectDeliverId")
                        .IsUnique();

                    b.HasIndex("CustomerId");

                    b.HasIndex("PartnerId");

                    b.ToTable("OS_Destinies");
                });

            modelBuilder.Entity("Domain.Entities.Outsourced.ElectronicRepair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Item")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordEquipament")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Problem")
                        .HasColumnType("longtext");

                    b.Property<int>("ServiceProviderId")
                        .HasColumnType("int");

                    b.Property<string>("SolutionApplied")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserEquipament")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ServiceProviderId");

                    b.HasIndex("UserId");

                    b.ToTable("OS_ElectronicsRepairs");
                });

            modelBuilder.Entity("Domain.Entities.Profile.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("UserProfileImage")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("UserProfile");
                });

            modelBuilder.Entity("Domain.Entities.ServicesBench.BudgetService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CollectsDeliversCostsId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("DataDescription")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IsPresentVisuallyDescription")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsRemote")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ProblemAccordingCustomer")
                        .HasColumnType("longtext");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("StatusService")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CollectsDeliversCostsId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UserId");

                    b.ToTable("BS_BudgetsServices");
                });

            modelBuilder.Entity("Domain.Entities.ServicesBench.CollectDeliverCosts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CostFrom")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("RoundTrip")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("BS_CollectsDeliversCosts");
                });

            modelBuilder.Entity("Domain.Entities.ServicesBench.Price", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("PriceService")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("ServiceName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("BS_Prices");
                });

            modelBuilder.Entity("Domain.Entities.ServicesBench.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ExecutedServicesComments")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Finished")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("IsAuthorized")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Started")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BS_Services");
                });

            modelBuilder.Entity("Domain.Entities.ServicesBench.TableProvidedServicePrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceService")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ServiceName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("BS_TableProvidedServicesPrices");
                });

            modelBuilder.Entity("Domain.Entities.Shared.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("Complement")
                        .HasColumnType("longtext");

                    b.Property<string>("District")
                        .HasColumnType("longtext");

                    b.Property<string>("Number")
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.Property<string>("Street")
                        .HasColumnType("longtext");

                    b.Property<string>("ZipCode")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SD_Addresses");
                });

            modelBuilder.Entity("Domain.Entities.Shared.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cel")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Landline")
                        .HasColumnType("longtext");

                    b.Property<string>("Site")
                        .HasColumnType("longtext");

                    b.Property<string>("Zap")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SD_Contacts");
                });

            modelBuilder.Entity("Domain.Entities.Shared.SocialNetwork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ContactId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.ToTable("SD_socialnetworks");
                });

            modelBuilder.Entity("Domain.Entities.StkProduct.Equipament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("longtext");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Segment")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Model")
                        .IsUnique();

                    b.ToTable("PD_Equipaments");
                });

            modelBuilder.Entity("Domain.Entities.StkProduct.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("EquipamentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("EquipamentId");

                    b.ToTable("PD_Products");
                });

            modelBuilder.Entity("Domain.Entities.StkProduct.Quantity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("IsReserved")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsTested")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NfNumber")
                        .HasColumnType("longtext");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("ReservedOrSoldByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Sn")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("SoldDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("SoldPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<string>("UsedHistorical")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("WarrantyEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("WarrantyEndLocal")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ReservedOrSoldByUserId");

                    b.HasIndex("Sn")
                        .IsUnique();

                    b.HasIndex("SupplierId");

                    b.ToTable("PD_Quantities");
                });

            modelBuilder.Entity("Domain.Entities.StkProduct.Tracking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("NfNumber")
                        .HasColumnType("longtext");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Sn")
                        .HasColumnType("longtext");

                    b.Property<decimal>("SoldPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("PD_Trackings");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("aspnetRoles");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole<int>");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("aspnetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("aspnetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser<int>");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("aspnetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("longtext");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("aspnetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Domain.Entities.Authentication.Role", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole<int>");

                    b.HasDiscriminator().HasValue("Role");
                });

            modelBuilder.Entity("Domain.Entities.Authentication.MyUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser<int>");

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("ContactId")
                        .HasColumnType("int");

                    b.Property<string>("Group")
                        .HasColumnType("longtext");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("int");

                    b.HasIndex("AddressId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ContactId");

                    b.HasIndex("ProfileId");

                    b.HasDiscriminator().HasValue("MyUser");
                });

            modelBuilder.Entity("Domain.Entities.Authentication.UserRole", b =>
                {
                    b.HasOne("Domain.Entities.Authentication.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Authentication.MyUser", "MyUser")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MyUser");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.Fill.StkProduct.Equipament_Fill", b =>
                {
                    b.HasOne("Domain.Entities.Main.Companies.Company", "Company")
                        .WithMany("Equipament_Fillers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Domain.Entities.Fill.StkProduct.Manufacturer_Fill", b =>
                {
                    b.HasOne("Domain.Entities.Main.Companies.Company", "Company")
                        .WithMany("Manufacturer_Fillers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Domain.Entities.Fill.StkProduct.Segment_Fill", b =>
                {
                    b.HasOne("Domain.Entities.Main.Companies.Company", "Company")
                        .WithMany("Segment_Fillers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Domain.Entities.Finances.FinancialBankAccount", b =>
                {
                    b.HasOne("Domain.Entities.Main.Companies.Company", "Company")
                        .WithMany("BankAccounts")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Domain.Entities.Finances.FinancialCard", b =>
                {
                    b.HasOne("Domain.Entities.Finances.FinancialBankAccount", "BankAccount")
                        .WithMany("Cards")
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankAccount");
                });

            modelBuilder.Entity("Domain.Entities.Finances.FinancialEssentialExpenses", b =>
                {
                    b.HasOne("Domain.Entities.Finances.FinancialBankAccount", "BankAccount")
                        .WithMany()
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Finances.FinancialExpenses", "Expenses")
                        .WithMany("EssentialExpenses")
                        .HasForeignKey("ExpensesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Authentication.MyUser", "User")
                        .WithMany("EssentialExpenses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankAccount");

                    b.Navigation("Expenses");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Finances.FinancialExpenses", b =>
                {
                    b.HasOne("Domain.Entities.Main.Companies.Company", "Company")
                        .WithMany("Expenses")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Domain.Entities.Finances.FinancialExpensesNotPredictable", b =>
                {
                    b.HasOne("Domain.Entities.Finances.FinancialBankAccount", "BankAccount")
                        .WithMany()
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Finances.FinancialExpenses", "Expenses")
                        .WithMany("ExpensesNotPredictables")
                        .HasForeignKey("ExpensesId");

                    b.HasOne("Domain.Entities.Authentication.MyUser", "User")
                        .WithMany("ExpensesNotPredictables")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankAccount");

                    b.Navigation("Expenses");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Main.Companies.Company", b =>
                {
                    b.HasOne("Domain.Entities.Shared.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("Domain.Entities.Shared.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId");

                    b.Navigation("Address");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("Domain.Entities.Main.Customers.Customer", b =>
                {
                    b.HasOne("Domain.Entities.Shared.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("Domain.Entities.Main.Companies.Company", "Company")
                        .WithMany("Customers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Shared.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId");

                    b.HasOne("Domain.Entities.Main.Inheritances.PhysicallyMovingCosts", "PhysicallyMovingCosts")
                        .WithMany()
                        .HasForeignKey("PhysicallyMovingCostsId");

                    b.Navigation("Address");

                    b.Navigation("Company");

                    b.Navigation("Contact");

                    b.Navigation("PhysicallyMovingCosts");
                });

            modelBuilder.Entity("Domain.Entities.Main.Partner", b =>
                {
                    b.HasOne("Domain.Entities.Shared.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("Domain.Entities.Main.Companies.Company", "Company")
                        .WithMany("Partners")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Shared.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId");

                    b.HasOne("Domain.Entities.Main.Inheritances.PhysicallyMovingCosts", "PhysicallyMovingCosts")
                        .WithMany()
                        .HasForeignKey("PhysicallyMovingCostsId");

                    b.Navigation("Address");

                    b.Navigation("Company");

                    b.Navigation("Contact");

                    b.Navigation("PhysicallyMovingCosts");
                });

            modelBuilder.Entity("Domain.Entities.Outsourced.BillingFrom", b =>
                {
                    b.HasOne("Domain.Entities.Main.Customers.Customer", "Customer")
                        .WithMany("BillingFromCollectsDelivers")
                        .HasForeignKey("CustomerId");

                    b.HasOne("Domain.Entities.Main.Partner", "Partner")
                        .WithMany("BillingFromCollectsDelivers")
                        .HasForeignKey("PartnerId");

                    b.Navigation("Customer");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("Domain.Entities.Outsourced.CollectDeliver", b =>
                {
                    b.HasOne("Domain.Entities.Outsourced.BillingFrom", "BillingFrom")
                        .WithMany()
                        .HasForeignKey("BillingFromId");

                    b.HasOne("Domain.Entities.Main.Companies.Company", "Company")
                        .WithMany("CollectsDelivers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Main.Partner", "Transporter")
                        .WithMany("CollectDeliversTransporters")
                        .HasForeignKey("TransporterId");

                    b.HasOne("Domain.Entities.Authentication.MyUser", "User")
                        .WithMany("CollectsDelivers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillingFrom");

                    b.Navigation("Company");

                    b.Navigation("Transporter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Outsourced.Destiny", b =>
                {
                    b.HasOne("Domain.Entities.Outsourced.CollectDeliver", "CollectDeliver")
                        .WithOne("Destiny")
                        .HasForeignKey("Domain.Entities.Outsourced.Destiny", "CollectDeliverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Main.Customers.Customer", "Customer")
                        .WithMany("CollectDeliverDestinies")
                        .HasForeignKey("CustomerId");

                    b.HasOne("Domain.Entities.Main.Partner", "Partner")
                        .WithMany("CollectDeliverDestinies")
                        .HasForeignKey("PartnerId");

                    b.Navigation("CollectDeliver");

                    b.Navigation("Customer");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("Domain.Entities.Outsourced.ElectronicRepair", b =>
                {
                    b.HasOne("Domain.Entities.Main.Companies.Company", "Company")
                        .WithMany("ElectronicsRepairs")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Main.Customers.Customer", "Customer")
                        .WithMany("ElectronicsRepairs")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Main.Partner", "ServiceProvider")
                        .WithMany("ElectronicsRepairs")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Authentication.MyUser", "User")
                        .WithMany("ElectronicsRepairs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Customer");

                    b.Navigation("ServiceProvider");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.ServicesBench.BudgetService", b =>
                {
                    b.HasOne("Domain.Entities.ServicesBench.CollectDeliverCosts", "CollectsDeliversCosts")
                        .WithMany()
                        .HasForeignKey("CollectsDeliversCostsId");

                    b.HasOne("Domain.Entities.Main.Companies.Company", "Company")
                        .WithMany("ServicesExecuted")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Main.Customers.Customer", "Customer")
                        .WithMany("ServicesExecuted")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ServicesBench.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId");

                    b.HasOne("Domain.Entities.Authentication.MyUser", "User")
                        .WithMany("BudgetsServices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CollectsDeliversCosts");

                    b.Navigation("Company");

                    b.Navigation("Customer");

                    b.Navigation("Service");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.ServicesBench.Price", b =>
                {
                    b.HasOne("Domain.Entities.ServicesBench.Service", "Service")
                        .WithMany("Prices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Domain.Entities.ServicesBench.Service", b =>
                {
                    b.HasOne("Domain.Entities.Authentication.MyUser", "User")
                        .WithMany("Services")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.ServicesBench.TableProvidedServicePrice", b =>
                {
                    b.HasOne("Domain.Entities.Main.Companies.Company", "Company")
                        .WithMany("TableProvidedServicesPrices")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Domain.Entities.Shared.SocialNetwork", b =>
                {
                    b.HasOne("Domain.Entities.Shared.Contact", "Contact")
                        .WithMany("socialnetworks")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("Domain.Entities.StkProduct.Product", b =>
                {
                    b.HasOne("Domain.Entities.Main.Companies.Company", "Company")
                        .WithMany("Products")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.StkProduct.Equipament", "Equipament")
                        .WithMany()
                        .HasForeignKey("EquipamentId");

                    b.Navigation("Company");

                    b.Navigation("Equipament");
                });

            modelBuilder.Entity("Domain.Entities.StkProduct.Quantity", b =>
                {
                    b.HasOne("Domain.Entities.Main.Customers.Customer", "Customer")
                        .WithMany("ProductsQuantities")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.StkProduct.Product", "Product")
                        .WithMany("Quantities")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Authentication.MyUser", "ReservedOrSoldByUser")
                        .WithMany("ProductsReserveds")
                        .HasForeignKey("ReservedOrSoldByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.Main.Partner", "Supplier")
                        .WithMany("ProductsQuantities")
                        .HasForeignKey("SupplierId");

                    b.Navigation("Customer");

                    b.Navigation("Product");

                    b.Navigation("ReservedOrSoldByUser");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Domain.Entities.StkProduct.Tracking", b =>
                {
                    b.HasOne("Domain.Entities.Main.Customers.Customer", "Customer")
                        .WithMany("Trackings")
                        .HasForeignKey("CustomerId");

                    b.HasOne("Domain.Entities.StkProduct.Product", "Product")
                        .WithMany("Trackings")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Authentication.MyUser", "User")
                        .WithMany("Trackings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Authentication.MyUser", b =>
                {
                    b.HasOne("Domain.Entities.Shared.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("Domain.Entities.Main.Companies.Company", "Company")
                        .WithMany("MyUsers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Shared.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId");

                    b.HasOne("Domain.Entities.Profile.UserProfile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId");

                    b.Navigation("Address");

                    b.Navigation("Company");

                    b.Navigation("Contact");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Domain.Entities.Finances.FinancialBankAccount", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("Domain.Entities.Finances.FinancialExpenses", b =>
                {
                    b.Navigation("EssentialExpenses");

                    b.Navigation("ExpensesNotPredictables");
                });

            modelBuilder.Entity("Domain.Entities.Main.Companies.Company", b =>
                {
                    b.Navigation("BankAccounts");

                    b.Navigation("CollectsDelivers");

                    b.Navigation("Customers");

                    b.Navigation("ElectronicsRepairs");

                    b.Navigation("Equipament_Fillers");

                    b.Navigation("Expenses");

                    b.Navigation("Manufacturer_Fillers");

                    b.Navigation("MyUsers");

                    b.Navigation("Partners");

                    b.Navigation("Products");

                    b.Navigation("Segment_Fillers");

                    b.Navigation("ServicesExecuted");

                    b.Navigation("TableProvidedServicesPrices");
                });

            modelBuilder.Entity("Domain.Entities.Main.Customers.Customer", b =>
                {
                    b.Navigation("BillingFromCollectsDelivers");

                    b.Navigation("CollectDeliverDestinies");

                    b.Navigation("ElectronicsRepairs");

                    b.Navigation("ProductsQuantities");

                    b.Navigation("ServicesExecuted");

                    b.Navigation("Trackings");
                });

            modelBuilder.Entity("Domain.Entities.Main.Partner", b =>
                {
                    b.Navigation("BillingFromCollectsDelivers");

                    b.Navigation("CollectDeliverDestinies");

                    b.Navigation("CollectDeliversTransporters");

                    b.Navigation("ElectronicsRepairs");

                    b.Navigation("ProductsQuantities");
                });

            modelBuilder.Entity("Domain.Entities.Outsourced.CollectDeliver", b =>
                {
                    b.Navigation("Destiny");
                });

            modelBuilder.Entity("Domain.Entities.ServicesBench.Service", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("Domain.Entities.Shared.Contact", b =>
                {
                    b.Navigation("socialnetworks");
                });

            modelBuilder.Entity("Domain.Entities.StkProduct.Product", b =>
                {
                    b.Navigation("Quantities");

                    b.Navigation("Trackings");
                });

            modelBuilder.Entity("Domain.Entities.Authentication.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Domain.Entities.Authentication.MyUser", b =>
                {
                    b.Navigation("BudgetsServices");

                    b.Navigation("CollectsDelivers");

                    b.Navigation("ElectronicsRepairs");

                    b.Navigation("EssentialExpenses");

                    b.Navigation("ExpensesNotPredictables");

                    b.Navigation("ProductsReserveds");

                    b.Navigation("Services");

                    b.Navigation("Trackings");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
