export class BusinessDataReceitaWs {
  abertura: string;
  situacao: string;
  tipo: string;
  nome: string;
  porte: string;
  natureza_juridica: string;
  atividade_principal: { code: string; text: string }[];
  atividades_secundarias: { code: string; text: string }[];
  logradouro: string;
  numero: string;
  municipio: string;
  bairro: string;
  uf: string;
  cep: string;
  email: string;
  telefone: string;
  data_situacao: string;
  cnpj: string;
  ultima_atualizacao: string;
  status: string;
  fantasia: string;
  complemento: string;
  efr: string;
  motivo_situacao: string;
  situacao_especial: string;
  data_situacao_especial: string;
  capital_social: string;
  qsa: any[];
  extra: any;
  billing: { free: boolean; database: boolean };
}
<<<<<<< HEAD

// export class BusinessData {
//   uf: string;
//   cep: string;
//   qsa: any[];
//   cnpj: string;
//   pais: any;
//   email: any;
//   porte: string;
//   bairro: string;
//   numero: string;
//   ddd_fax: string;
//   municipio: string;
//   logradouro: string;
//   cnae_fiscal: number;
//   codigo_pais: any;
//   complemento: string;
//   codigo_porte: number;
//   razao_social: string;
//   nome_fantasia: string;
//   capital_social: number;
//   ddd_telefone_1: string;
//   ddd_telefone_2: string;
//   opcao_pelo_mei: boolean;
//   descricao_porte: string;
//   codigo_municipio: number;
//   cnaes_secundarios: { codigo: number, descricao: string }[];
//   natureza_juridica: string;
//   situacao_especial: string;
//   opcao_pelo_simples: boolean;
//   situacao_cadastral: number;
//   data_opcao_pelo_mei: string;
//   data_exclusao_do_mei: any;
//   cnae_fiscal_descricao: string;
//   codigo_municipio_ibge: number;
//   data_inicio_atividade: string;
//   data_situacao_especial: any;
//   data_opcao_pelo_simples: string;
//   data_situacao_cadastral: string;
//   nome_cidade_no_exterior: string;
//   codigo_natureza_juridica: number;
//   data_exclusao_do_simples: any;
//   motivo_situacao_cadastral: number;
//   ente_federativo_responsavel: string;
//   identificador_matriz_filial: number;
//   qualificacao_do_responsavel: number;
//   descricao_situacao_cadastral: string;
//   descricao_tipo_de_logradouro: string;
//   descricao_motivo_situacao_cadastral: string;
//   descricao_identificador_matriz_filial: string;

// }
=======
export class BusinessData {
  uf: string;
  cep: string;
  qsa: any[];
  cnpj: string;
  pais: any;
  email: any;
  porte: string;
  bairro: string;
  numero: string;
  ddd_fax: string;
  municipio: string;
  logradouro: string;
  cnae_fiscal: number;
  codigo_pais: any;
  complemento: string;
  codigo_porte: number;
  razao_social: string;
  nome_fantasia: string;
  capital_social: number;
  ddd_telefone_1: string;
  ddd_telefone_2: string;
  opcao_pelo_mei: boolean;
  descricao_porte: string;
  codigo_municipio: number;
  cnaes_secundarios: { codigo: number, descricao: string }[];
  natureza_juridica: string;
  situacao_especial: string;
  opcao_pelo_simples: boolean;
  situacao_cadastral: number;
  data_opcao_pelo_mei: string;
  data_exclusao_do_mei: any;
  cnae_fiscal_descricao: string;
  codigo_municipio_ibge: number;
  data_inicio_atividade: string;
  data_situacao_especial: any;
  data_opcao_pelo_simples: string;
  data_situacao_cadastral: string;
  nome_cidade_no_exterior: string;
  codigo_natureza_juridica: number;
  data_exclusao_do_simples: any;
  motivo_situacao_cadastral: number;
  ente_federativo_responsavel: string;
  identificador_matriz_filial: number;
  qualificacao_do_responsavel: number;
  descricao_situacao_cadastral: string;
  descricao_tipo_de_logradouro: string;
  descricao_motivo_situacao_cadastral: string;
  descricao_identificador_matriz_filial: string;

}
>>>>>>> 3b35903493532fbd461ebfb3e4028536631f3f3e
